path = 'frontend/src/AdminDashboard.jsx'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# ── PATCH 1: Replace serviceTotal calculation ──────────────────────────────────
old1 = (
    "                                    const groupPrice = (groupEditingItem?.price || svcInfo?.basePrice || 0);\n"
    "                                    const serviceTotal = isGlobalSvc \n"
    "                                      ? ((groupEditingItem?.weight || 0) * groupPrice)\n"
    "                                      : serviceItems.reduce((acc, item) => {\n"
    "                                          const editingItem = currentOrderItems.find(i => i._id === item._id);\n"
    "                                          return acc + ((editingItem?.weight > 0) ? (editingItem.weight * (editingItem.price || 0)) : ((editingItem?.quantity || 0) * (editingItem?.price || 0)));\n"
    "                                        }, 0);"
)

new1 = (
    "                                    const groupPrice = (groupEditingItem?.price || svcInfo?.basePrice || 0);\n"
    "                                    const totalWeight = groupEditingItem?.weight || 0;\n"
    "                                    const subKgDeducted = (o.subscriptionApplied && isGlobalSvc) ? (o.subscriptionKgDeducted || 0) : 0;\n"
    "                                    const overageKg = Math.max(0, totalWeight - subKgDeducted);\n"
    "                                    const isFullyCovered = o.subscriptionApplied && isGlobalSvc && overageKg === 0 && totalWeight > 0;\n"
    "                                    const serviceTotal = isGlobalSvc\n"
    "                                      ? (o.subscriptionApplied ? overageKg * groupPrice : totalWeight * groupPrice)\n"
    "                                      : serviceItems.reduce((acc, item) => {\n"
    "                                          const editingItem = currentOrderItems.find(i => i._id === item._id);\n"
    "                                          return acc + ((editingItem?.weight > 0) ? (editingItem.weight * (editingItem.price || 0)) : ((editingItem?.quantity || 0) * (editingItem?.price || 0)));\n"
    "                                        }, 0);"
)

assert old1 in content, "PATCH 1 target not found"
content = content.replace(old1, new1, 1)

# ── PATCH 2: Replace the Global service header + rate column rendering ─────────
old2 = (
    "                                          <td colSpan={isGlobalSvc ? 2 : 4} style={{ padding: '1rem 1.25rem', borderBottom: '2px solid rgba(91,62,132,0.1)' }}>\n"
    "                                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.85rem' }}>\n"
    "                                              <div style={{ width: '4px', height: '18px', background: 'var(--color-primary)', borderRadius: '10px' }}></div>\n"
    "                                              <span style={{ fontWeight: 900, color: '#5b3e84', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.15em' }}>\n"
    "                                                {serviceName}\n"
    "                                              </span>\n"
    "                                            </div>\n"
    "                                          </td>\n"
    "                                          {isGlobalSvc ? (\n"
    "                                            <>\n"
    "                                              <td style={{ padding: '1rem', textAlign: 'center' }}>\n"
    "                                                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.6rem' }}>\n"
    "                                                  <input \n"
    "                                                    type=\"number\" \n"
    "                                                    className=\"adm-input\" \n"
    "                                                    style={{ \n"
    "                                                      width: '85px', textAlign: 'center', padding: '0.5rem',\n"
    "                                                      borderRadius: '10px', border: '2px solid var(--color-primary)',\n"
    "                                                      background: '#fff', fontWeight: 900, transition: 'all 0.2s',\n"
    "                                                      boxShadow: '0 2px 8px rgba(91,62,132,0.1)'\n"
    "                                                    }} \n"
    "                                                    value={groupEditingItem?.weight ?? ''} \n"
    "                                                    onChange={e => handleGroupWeightUpdate(o._id, serviceName, e.target.value)}\n"
    "                                                  />\n"
    "                                                  <span style={{ fontSize: '0.75rem', color: 'var(--color-primary)', fontWeight: 800 }}>KG</span>\n"
    "                                                </div>\n"
    "                                              </td>\n"
    "                                              <td style={{ padding: '1rem', textAlign: 'right' }}>\n"
    "                                                {o.subscriptionApplied ? (\n"
    "                                                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', background: 'linear-gradient(135deg, #7c3aed22, #5b3e8422)', padding: '0.4rem 0.85rem', borderRadius: '100px', border: '1.5px solid #7c3aed55' }}>\n"
    "                                                    <span style={{ fontSize: '0.75rem' }}>⚡</span>\n"
    "                                                    <span style={{ fontSize: '0.75rem', fontWeight: 800, color: '#7c3aed' }}>Subscription Rate</span>\n"
    "                                                  </div>\n"
    "                                                ) : (\n"
    "                                                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.5rem' }}>\n"
    "                                                    <span style={{ fontSize: '0.9rem', color: '#5b3e84', fontWeight: 800 }}>₹</span>\n"
    "                                                    <input \n"
    "                                                      type=\"number\" \n"
    "                                                      className=\"adm-input\" \n"
    "                                                      style={{ \n"
    "                                                        width: '75px', textAlign: 'right', padding: '0.5rem', fontSize: '0.9rem',\n"
    "                                                        borderRadius: '10px', border: '1.5px solid rgba(91,62,132,0.1)',\n"
    "                                                        background: '#fff', fontWeight: 700\n"
    "                                                      }} \n"
    "                                                      value={groupEditingItem?.price || svcInfo?.basePrice || ''} \n"
    "                                                      onChange={e => handleGroupPriceUpdate(o._id, serviceName, e.target.value)}\n"
    "                                                    />\n"
    "                                                    <span style={{ fontSize: '0.75rem', fontWeight: 800 }}>/kg</span>\n"
    "                                                  </div>\n"
    "                                                )}\n"
    "                                              </td>\n"
    "                                              <td style={{ padding: '1rem', textAlign: 'right', fontWeight: 900, color: '#5b3e84', fontSize: '1.2rem' }}>\n"
    "                                                ₹{serviceTotal.toLocaleString()}\n"
    "                                              </td>\n"
    "                                            </>\n"
    "                                          ) : (\n"
    "                                            <td style={{ padding: '1rem', textAlign: 'right', fontWeight: 900, color: '#5b3e84', fontSize: '1.2rem' }}>\n"
    "                                              ₹{serviceTotal.toLocaleString()}\n"
    "                                            </td>\n"
    "                                          )}"
)

new2 = (
    "                                          <td colSpan={isGlobalSvc ? 2 : 4} style={{ padding: '1rem 1.25rem', borderBottom: '2px solid rgba(91,62,132,0.1)' }}>\n"
    "                                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.85rem', flexWrap: 'wrap' }}>\n"
    "                                              <div style={{ width: '4px', height: '18px', background: 'var(--color-primary)', borderRadius: '10px' }}></div>\n"
    "                                              <span style={{ fontWeight: 900, color: '#5b3e84', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.15em' }}>\n"
    "                                                {serviceName}\n"
    "                                              </span>\n"
    "                                              {o.subscriptionApplied && isGlobalSvc && (\n"
    "                                                <span style={{ fontSize: '0.65rem', fontWeight: 800, color: '#7c3aed', background: '#7c3aed15', border: '1px solid #7c3aed33', padding: '0.15rem 0.5rem', borderRadius: '100px' }}>\n"
    "                                                  ⚡ {subKgDeducted}kg free by subscription\n"
    "                                                </span>\n"
    "                                              )}\n"
    "                                            </div>\n"
    "                                          </td>\n"
    "                                          {isGlobalSvc ? (\n"
    "                                            <>\n"
    "                                              <td style={{ padding: '1rem', textAlign: 'center' }}>\n"
    "                                                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.6rem' }}>\n"
    "                                                  <input \n"
    "                                                    type=\"number\" \n"
    "                                                    className=\"adm-input\" \n"
    "                                                    style={{ \n"
    "                                                      width: '85px', textAlign: 'center', padding: '0.5rem',\n"
    "                                                      borderRadius: '10px', border: '2px solid var(--color-primary)',\n"
    "                                                      background: '#fff', fontWeight: 900, transition: 'all 0.2s',\n"
    "                                                      boxShadow: '0 2px 8px rgba(91,62,132,0.1)'\n"
    "                                                    }} \n"
    "                                                    value={groupEditingItem?.weight ?? ''} \n"
    "                                                    onChange={e => handleGroupWeightUpdate(o._id, serviceName, e.target.value)}\n"
    "                                                  />\n"
    "                                                  <span style={{ fontSize: '0.75rem', color: 'var(--color-primary)', fontWeight: 800 }}>KG</span>\n"
    "                                                </div>\n"
    "                                                {o.subscriptionApplied && totalWeight > 0 && (\n"
    "                                                  <div style={{ marginTop: '0.3rem', fontSize: '0.62rem', fontWeight: 700, color: isFullyCovered ? '#16a34a' : '#f59e0b', textAlign: 'center' }}>\n"
    "                                                    {isFullyCovered\n"
    "                                                      ? `✓ All ${totalWeight}kg covered`\n"
    "                                                      : `${subKgDeducted}kg free · ${overageKg}kg chargeable`}\n"
    "                                                  </div>\n"
    "                                                )}\n"
    "                                              </td>\n"
    "                                              <td style={{ padding: '1rem', textAlign: 'right' }}>\n"
    "                                                {isFullyCovered ? (\n"
    "                                                  <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', background: '#16a34a15', padding: '0.4rem 0.85rem', borderRadius: '100px', border: '1.5px solid #16a34a33' }}>\n"
    "                                                    <span style={{ fontSize: '0.75rem', fontWeight: 800, color: '#16a34a' }}>✓ Free</span>\n"
    "                                                  </div>\n"
    "                                                ) : (\n"
    "                                                  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.25rem' }}>\n"
    "                                                    {o.subscriptionApplied && overageKg > 0 && (\n"
    "                                                      <div style={{ fontSize: '0.62rem', color: '#f59e0b', fontWeight: 700 }}>\n"
    "                                                        {overageKg}kg @ rate below\n"
    "                                                      </div>\n"
    "                                                    )}\n"
    "                                                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>\n"
    "                                                      <span style={{ fontSize: '0.9rem', color: '#5b3e84', fontWeight: 800 }}>₹</span>\n"
    "                                                      <input \n"
    "                                                        type=\"number\" \n"
    "                                                        className=\"adm-input\" \n"
    "                                                        style={{ \n"
    "                                                          width: '75px', textAlign: 'right', padding: '0.5rem', fontSize: '0.9rem',\n"
    "                                                          borderRadius: '10px', border: '1.5px solid rgba(91,62,132,0.1)',\n"
    "                                                          background: '#fff', fontWeight: 700\n"
    "                                                        }} \n"
    "                                                        value={groupEditingItem?.price || svcInfo?.basePrice || ''} \n"
    "                                                        onChange={e => handleGroupPriceUpdate(o._id, serviceName, e.target.value)}\n"
    "                                                      />\n"
    "                                                      <span style={{ fontSize: '0.75rem', fontWeight: 800 }}>/kg</span>\n"
    "                                                    </div>\n"
    "                                                  </div>\n"
    "                                                )}\n"
    "                                              </td>\n"
    "                                              <td style={{ padding: '1rem', textAlign: 'right', fontWeight: 900, color: isFullyCovered ? '#16a34a' : '#5b3e84', fontSize: '1.2rem' }}>\n"
    "                                                {isFullyCovered ? '₹0' : `₹${serviceTotal.toLocaleString()}`}\n"
    "                                              </td>\n"
    "                                            </>\n"
    "                                          ) : (\n"
    "                                            <td style={{ padding: '1rem', textAlign: 'right', fontWeight: 900, color: '#5b3e84', fontSize: '1.2rem' }}>\n"
    "                                              ₹{serviceTotal.toLocaleString()}\n"
    "                                            </td>\n"
    "                                          )}"
)

assert old2 in content, "PATCH 2 target not found"
content = content.replace(old2, new2, 1)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print("✅ Both patches applied successfully")
